### ISSUE TITLE
support for authentication

### ISSUE THREAD

**Issue by cometta** [exacaster/lighter#182]
Any plan to support for authentication, so that when using sparkmagic, we can authorize user first, before allow to connect to lighter server? I have scenario where we have 2 different team, each team should not able to access each other data.

**Comment by pdambrauskas** [comment]
When Lighter is deployed on K8s, it can be protected by enabling Basic Auth on Ingress level. Most of Ingress controllers supports it. Example on how to do it on NGINX: https://kubernetes.github.io/ingress-nginx/examples/auth/basic/


We should probably mention it in our documentation, since it is not the first time when this question was asked 😄 : https://github.com/exacaster/lighter/issues/30
