### ISSUE TITLE
Parallelle code execution in one Lighter Session

### ISSUE THREAD

**Issue by wjxiz1992** [exacaster/lighter#308]
Hi lighter experts,

similar to this issue in Livy: https://issues.apache.org/jira/browse/LIVY-395, I am wondering if lighter could support parallel code execution in one lighter session.
Currently I've tried to run 2 notebook cells at the same time, but I found the second cell's code will not be processed by lighter until the first cell is done.
This feature is useful when I set a fair scheduler for Spark and run several code snippets together.

**Comment by Minutis** [comment]
Hello @wjxiz1992,

could you please give more details on the possible use cases? Because from our perspective usually, you use a single Notebook to achieve a single end result. Also, most of the time the lineage of the cells is important since you use the variables defined in cells that precede the currently running one.

Is running two notebooks in parallel is out of the question?

**Comment by wjxiz1992** [comment]
Thanks a lot! You are reasonable, close it for now.
